### ISSUE TITLE
ZBytes: tuple serialization\deserialization support

### ISSUE THREAD

**Issue by yellowhatter** [eclipse-zenoh/zenoh-cpp#226]
### Describe the feature

Need to add tuple support to align with Rust

**Comment by DenisBiryukov91** [comment]
But there are no tuples in c, similar functionality can be achieved with z_bytes_reader_read_bounded.

**Comment by yellowhatter** [comment]
Well, I think we need to utilise C++ capabilities and support recurring
over any std::tuple size, disregarding how it is made in other languages?
Or we are going to break interoperability then?

чт, 19 сент. 2024 г., 18:18 DenisBiryukov91 ***@***.***>:

**Comment by DenisBiryukov91** [comment]
done by #238.
