### ISSUE TITLE
Fixing the redundency

### ISSUE THREAD

**Issue by OmerFarukBOUN** [eclipse-zenoh/zenoh-cpp#268]
### Describe the feature

https://github.com/eclipse-zenoh/zenoh-cpp/blob/b5fca3e302dc74a57895dffae9df4f2089ed243c/examples/universal/z_sub.cxx#L44
In this line the {"key_expression", &expr} part is redundant. In [getargs.h](https://github.com/eclipse-zenoh/zenoh-cpp/blob/main/examples/getargs.h), it parses this input but does nothing with it and this argument does not affect the "config" object. Since it is in the example codes, it makes the reader to believe it is necessary. There are more places that this was used. 
Please delete these redundant parts.

**Comment by DenisBiryukov91** [comment]
This part is not redundant, it is used to parse optional key_expression argument value into &expr.
