### ISSUE TITLE
[Doc] Build with unstable API and SHM features  

### ISSUE THREAD

**Issue by YuanYuYuan** [eclipse-zenoh/zenoh-cpp#333]
### Description

We should either give examples to show how to build zenoh-cpp with the unstable API and the SHM feature or add the links to the corresponding tutorial in zenoh-c and zenoh-pico.

**Comment by YuanYuYuan** [comment]
It seems that we don't need to specify the feature flags if we build zenoh-cpp on top of an installed zenoh-c with cmake flags set. Then why do we still need them while building zenoh-cpp in the CI? https://github.com/eclipse-zenoh/zenoh-cpp/blob/e983fa88ea6fcbc9e190ab1c3e71a39b892ed55d/.github/workflows/ci.yml#L49C1-L49C158

**Comment by DenisBiryukov91** [comment]
> It seems that we don't need to specify the feature flags if we build zenoh-cpp on top of an installed zenoh-c with cmake flags set. Then why do we still need them while building zenoh-cpp in the CI? https://github.com/eclipse-zenoh/zenoh-cpp/blob/e983fa88ea6fcbc9e190ab1c3e71a39b892ed55d/.github/workflows/ci.yml#L49C1-L49C158

We do not need them, this is a (harmless) bug in ci.

**Comment by YuanYuYuan** [comment]
> We do not need them, this is a (harmless) bug in ci.

Yes. I agree. I copy & test it because there's no doc for how to build with unstable API. And then I just realized it's unneeded :smile: .
