### ISSUE TITLE
rename Reply::get to Reply::get_sample()

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-cpp#47]
### Describe the feature

It's not clear that `Reply::get` returns `Sample`. Better to reflect it in method's name: `get_sample`. This method corresponds to pair of C API methods: `z_reply_ok` and `z_reply_err`, so we are free to name it as we want, it's not bound to C API naming,

**Comment by DenisBiryukov91** [comment]
renamed into Reply::get_ok()
