### ISSUE TITLE
Enable build on Windows support

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-cpp#5]
At this moment build on windows is disabled due to compilation issues

**Comment by traversaro** [comment]
After:
* https://github.com/eclipse-zenoh/zenoh-cpp/pull/135
* https://github.com/eclipse-zenoh/zenoh-cpp/pull/134

The `zenohc` examples compile fine, while the `zenohpico` tests are not compiling. As `zenohpico` does not seem to fully support Windows (see https://github.com/eclipse-zenoh/zenoh-pico/issues/198 and the fact that `_Bool` is used in public interface, even if C++ projects on Windows can't consume it), probably it could make sense to avoid to compile `zenohpico` example on Windows for now?
