### ISSUE TITLE
No error/log print in subscriber example when using shared memory and shared memory is not configured [Bug] 

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-cpp#84]
### Describe the bug

When using shared memory over zenoh - additional configuration needs to be made, if not made the data will be sent over socket , and this will result with poor performance.

The expectation is either print a warning of wrong usage or fail the shared memory API

Same problem was fixed in zenoh-c - https://github.com/eclipse-zenoh/zenoh-c/issues/202
Zenoh-cpp publisher example should also report if shartd memory is misconfigured in zenoh-c mode: https://github.com/eclipse-zenoh/zenoh-cpp/blob/main/examples/universal/z_sub.cxx

### To reproduce

-

### System info

-

**Comment by Mallets** [comment]
@yellowhatter is this issue still relevant?
